const ActionTypes = {

	GITHUB_FETCH:"GITHUB_FETCH",
	GITHUB_SUCCESS:"GITHUB_SUCCESS",
	GITHUB_FAILED:"GITHUB_FAILED",
	
	GITHUB_FILE_FETCH:"GITHUB_FILE_FETCH",
	GITHUB_FILE_SUCCESS:"GITHUB_FILE_SUCCESS",
	GITHUB_FILE_FAILED:"GITHUB_FILE_FAILED",
	
	GITHUB_NOTEBOOK_FETCH:"GITHUB_NOTEBOOK_FETCH",
	GITHUB_NOTEBOOK_SUCCESS:"GITHUB_NOTEBOOK_SUCCESS",
	GITHUB_NOTEBOOK_FAILED:"GITHUB_NOTEBOOK_FAILED",
};

export default ActionTypes;